import { Logo } from "@/assets";
import Content from "@/Components/Content";
import Navbar from "@/Components/Navbar";
import Sidebar from "@/Components/Sidebar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cashon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={Logo} />
      </Head>
      <main className="flex h-full text-black bg-white">
        <div className="w-[16%] border-r-2">
          <Sidebar />
        </div>
        <div className="w-[84%]">
          <Navbar />
          <Content />
        </div>
      </main>
    </>
  );
}
